Repository AY2223S1-CS2103T-W15-2/tp, pull requests merged in 2022-10, with the labels that each got.

#73 Fix checkstyle and compile errors
  src/main/java/seedu/address/logic/commands/AddTagsToListingCommand.java
  src/main/java/seedu/address/logic/parser/AddTagsToListingCommandParser.java
Labels: type.Bug

#74 Fix bugs for Offer, update UG/DG and enable Assertions
  build.gradle
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddOfferCommand.java
  src/main/java/seedu/address/logic/parser/AddOfferCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/offer/UniqueOfferList.java
  src/main/java/seedu/address/storage/JsonAdaptedOffer.java
Labels: documentation, priority.High, type.Bug

#82 Update DeveloperGuide.md
  docs/DeveloperGuide.md
Labels: priority.High

#81 Implement Edit, Delete command for Offers
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteOfferCommand.java
  src/main/java/seedu/address/logic/commands/EditOfferCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteOfferCommandParser.java
  src/main/java/seedu/address/logic/parser/EditOfferCommandParser.java
Labels: priority.High

#87 Update UG and commands
  docs/UserGuide.md
  docs/images/helpMessage.png
  src/main/java/seedu/address/logic/commands/AddClientCommand.java
  src/main/java/seedu/address/logic/commands/AddListingCommand.java
  src/main/java/seedu/address/logic/commands/AddOfferCommand.java
  src/main/java/seedu/address/logic/commands/AddPersonCommand.java
  src/main/java/seedu/address/logic/commands/DeleteClientCommand.java
  src/main/java/seedu/address/logic/commands/DeleteListingCommand.java
  src/main/java/seedu/address/logic/commands/DeletePersonCommand.java
  src/main/java/seedu/address/logic/commands/EditClientCommand.java
  src/main/java/seedu/address/logic/commands/EditListingCommand.java
  src/main/java/seedu/address/logic/commands/EditPersonCommand.java
  src/main/java/seedu/address/logic/commands/FindPersonCommand.java
  src/main/java/seedu/address/model/listing/ListingID.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
Labels: documentation, priority.High
